name: Update Flights

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 20 * * *'

jobs:
  update-flights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm update-statuses
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || { git commit -m "chore: update flight statuses $(date +'%Y-%m-%d')" && git push; }
